---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 60m
  install:
    remediation:
      retries: 10
  chart:
    spec:
      chart: traefik
      version: 28.2.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    deployment:
      replicas: 1
    logs:
      access:
        enabled: true
        format: json
    service:
      type: LoadBalancer
    ingressRoute:
      healthcheck:
        enabled: true
        matchRule: Host(`traefik.e3.cpressland.io`) && PathPrefix(`/ping`)
        entryPoints: ["websecure"]
