---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./bases/traefik/base
  force: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
