---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./bases/traefik/base
  force: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-config
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./bases/traefik/configuration
  dependsOn:
    - name: traefik
    - name: sealed-secrets
  force: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
